### ISSUE TITLE
Stopped working, cant Uninstall

### ISSUE THREAD

**Issue by zstoichev** [dim-stream-deck/com.dim.streamdeck#3]
DIM integration just stopped working today. Updated Stream Deck to recent version 6.0.2, but was not able to De-authorize the connection from DIM. Tried restarting the browser and PC, reloading DIM page, etc. in vain. Tried to uninstall the plugin from Deck, but it is not working, plugin remains installed. Current version 2.0.0. Any advise?
![image](https://user-images.githubusercontent.com/167830/210516832-d8a1508e-8395-4283-8325-6f96de065fbd.png)

**Comment by Sudiukil** [comment]
Same issue here.

Tried reinstalling the plugin to no avail. DIM won't de-authorize either.

**Comment by fcannizzaro** [comment]
Fixed (after the latest update of DIM)

**Comment by zstoichev** [comment]
Not sure it is related but I still cant uninstall the plugin. Here is a part of Deck logs:
20:07:07.594                     StreamDeck                        EGQTCredentialStore::DeletePasswordWithServerAndUserName(): CredDelete() - GetLastError() 1168
20:07:07.595                     StreamDeck                        ESDPluginManager::UninstallPluginWithPluginUUID(): Failed to delete C

**Comment by zstoichev** [comment]
Also, looks like DIM plugin is not working well:
20:33:02.007                     StreamDeck                        ESDObsConnectionManager::CreateSocket::<lambda_2aa1c9d242cae83e7007c40c4c7db86a>::operator ()(): SLOBS returned error Връзката е отказана
20:33:02.212                     StreamDeck                        ESDCustomPlugin::onNativeProcessFinished():     The plugin 'DIM Stream Deck' crashed with code -1073740791
20:33:02.212                     StreamDeck                        ESDCustomPlugin::restartNativeProcess():        Restarting plugin 'DIM Stream Deck' in 60 seconds(s)
